export const PostActions = {
  FETCH_POST_DATA: "FETCH_POST_DATA",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAILED: "FETCH_FAILED",

  CREATE_POST_DATA: "CREATE_POST_DATA",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILED: "CREATE_POST_FAILED",

  UPDATE_POST_DATA: "UPDATE_POST_DATA",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILED: "UPDATE_POST_FAILED",

  DELETE_POST_DATA: "DELETE_POST_DATA",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "DELETE_POST_FAILED",
};
