export const userActions = {
  FETCH_USER_DATA: "FETCH_USER_DATA",
  FETCH_USER_SUCCESS: "FETCH_SUCCESS",
  FETCH_USER_FAILED: "FETCH_FAILED",

  CREATE_USER_DATA: "CREATE_USER_DATA",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  LOGIN_USER_DATA: "LOGIN_USER_DATA",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED: "LOGIN_USER_FAILED",

  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  DELETE_USER_DATA: "DELETE_USER_DATA",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
};
